server {
   listen 443 http2;
   listen [::]:443 http2;
   ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;

   ssl on;
   ssl_certificate /etc/nginx/ssl_certs/mr2mato.ir/public.pem;
   ssl_certificate_key /etc/nginx/ssl_certs/mr2mato.ir/private.key;
   gzip on; gzip_vary on; gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;
   server_name dormitory.mr2mato.ir www.dormitory.mr2mato.ir;
   location /StaticFiles {
        autoindex on;
        alias /root/projects/Dormitory-ut/StaticFiles/;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100M;
        proxy_pass  http://127.0.0.1:15002;
    }
}
