# Generated by Django 4.1.3 on 2022-11-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='خوابگاه', max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='خوابگاه', max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('capacity', models.SmallIntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panel.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=64)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panel.room')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
