# Generated by Django 4.1.3 on 2022-12-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0002_setting_dorm_sex_userprofile_father_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_code',
            new_name='student_number',
        ),
    ]
