# Generated by Django 4.1.3 on 2022-12-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0003_rename_user_code_userprofile_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
