# Generated by Django 4.1.3 on 2023-01-02 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Panel', '0004_remove_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='sex',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='title',
            field=models.CharField(default='خوابگاه', max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.SmallIntegerField(default=1, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panel.dorm', verbose_name='خوابگاه مورد نظر'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='خوابگاه', max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_new_user',
            field=models.BooleanField(default=True, verbose_name='وضعیت ثبت نام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('کارشناسی', 'کارشناسی'), ('ارشد', 'ارشد'), ('دکترا', 'دکترا'), ('مدیر', 'مدیر')], default='کارشناسی', max_length=16, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_early_bird',
            field=models.BooleanField(default=False, verbose_name='سحر خیز بودن'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_native_born',
            field=models.BooleanField(default=True, verbose_name='بومی یا غیر بومی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_noisy',
            field=models.BooleanField(default=False, verbose_name='حساس به سر صدا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_paying',
            field=models.BooleanField(default=False, verbose_name='شبانه یا روزانه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='requested_roommate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='هم اتاقی مورد نظر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Panel.room', verbose_name='اتاق مورد نظر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت تاییدیه اتاق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.CharField(max_length=64, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
