# Generated by Django 4.1.3 on 2023-01-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0005_alter_dorm_code_alter_dorm_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dorm',
            options={'verbose_name': 'خوابگاه', 'verbose_name_plural': 'خوابگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل گاربری', 'verbose_name_plural': 'پروفایل های گاربری'},
        ),
    ]
