# Generated by Django 4.1.5 on 2023-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0006_alter_dorm_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_native_born',
            field=models.BooleanField(default=True, verbose_name='دانشجو بومی هستم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_paying',
            field=models.BooleanField(default=False, verbose_name='دانشجو شبانه هستم'),
        ),
    ]
